### ISSUE TITLE
Definitions of sites and virtualhosts is inconsistent

### ISSUE THREAD

**Issue by htgoebel** [plone/ansible.plone_server#23]
In defaults/main.yml only a single site can be defined, but in templates/restart_clients.sh.j2 several sites are referenced. This is inconsistent:
- defaults/main.yml uses `plone_site_id`, while the template uses `vh.zodb_path`
- the template uses `webserver_virtualhosts` which is not documented anywhere in this role.

I volunteer implementing the following (incompatible) change if you agree on it:
- Convert the site-related definitions into a list of sites (scratch):
```
plone_default_site:
  create: yes
  site_id: Plone
  default_language: en
  extension_profiles:
plone_sites = '{{ [ plone_default_site ] }}'
```
and then in templates/restart_clients.sh.j2 revere to these.

As I follow up, the ansible-playbook has to be adopted, which I volunteer to do, too.
