### ISSUE TITLE
Use it with the starzel.buildout

### ISSUE THREAD

**Issue by Gomez** [plone/ansible.plone_server#54]
I try to use this role with the starzel.buildout: https://github.com/starzel/buildout/ 

To make this work, i need to run a task before "Bootstrap buildout" like: 
```
$ ln -s local_develop.cfg local.cfg
```
Can i add some kind of switches for it as a PR (with good defaults)? Or is there an other way?

**Comment by Gomez** [comment]
I solved it temporarily with pre_tasks:

```
  pre_tasks:

    - name: Create plone project dir
      file:
        dest: "{{ servers[0]['plone_var_path'] }}"
        state: 'directory'

    - name: Copy starzel.buildout local.cfg to buildout dir
      copy:
        content: "[buildout]\nextends = local_develop.cfg\n"
        dest: "{{ servers[0]['plone_var_path'] }}/local.cfg"
        force: no

    - name: Copy starzel.buildout secret.cfg to buildout dir
      copy:
        content: "[buildout]\nlogin = admin\npassword = admin\n"
        dest: "{{ servers[0]['plone_var_path'] }}/secret.cfg"
        force: no
```
