### ISSUE TITLE
Add extends to buildout cache

### ISSUE THREAD

**Issue by Gomez** [plone/ansible.plone_server#98]
All our server use the extends cache, as it makes them more independent from third party downtimes.

We use a task like this:

```
- name: Copy the buildout default cfg template
  template:
    src: "buildout_default_cfg.j2"
    dest: '$home/.buildout/default.cfg'
```

With this template:
```
[buildout]
eggs-directory = $home/.buildout/eggs
download-cache = $home/.buildout/downloads
extends-cache  = $home/.buildout/extends
```

Should i prepare a PR for this?
